name: test

on:
  push:

jobs:
  bot:
    runs-on: ubuntu-20.04
    steps:
      - name: 获取本仓库源码...
        uses: actions/checkout@main

      - name: 清理环境...
        run: |
          echo test
          df -h
  
