name: test

on:
  push:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  bot:
    runs-on: ubuntu-20.04
    steps:
      - name: 获取本仓库源码...
        uses: actions/checkout@main

      - name: test
        run: |
          echo test
