name: test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: 获取本仓库源码...
        uses: actions/checkout@main

      - name: test
        run: |
          echo test
