name: test

on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: 'ROM_URL'
        required: true
        default: 'https://bigota.d.miui.com/V12.5.7.0.RJACNXM/miui_CMI_V12.5.7.0.RJACNXM_e895dd1b1a_11.0.zip'
      ZIP_NAME:
        description: 'ZIP_NAME'
        required: true
        default: 'miui_CMI_V12.5.7.0.RJACNXM_e895dd1b1a_11.0.zip'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: 获取本仓库源码...
        uses: actions/checkout@main

      - name: 创建目录...
        run: |
          cd $GITHUB_WORKSPACE
          mkdir Auto_Miui

      - name: 获取代号...
        run: |
          cd $GITHUB_WORKSPACE/Auto_Miui
          code=$(echo ${{ github.event.inputs.ZIP_NAME }} | cut -d _ -f 2| tr -d '\r' |tr -d '\n')
          echo $code
