name: test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: 获取本仓库源码...
        uses: actions/checkout@main

      - name: 安装环境...
        run: |
          sudo -E apt-get install python3 python3-pip default-jre -y
          pip install aliyunpan

      - name: 创建文件...
        run: |
          cd $GITHUB_WORKSPACE/aliyun
          dd if=/dev/zero of=hello.txt bs=100M count=1
      
      - name: 上传阿里云...
        run: |
          cd $GITHUB_WORKSPACE/aliyun
          today=$(date +%y.%-m.%-d)
          python main.py upload hello.txt AcmeTeam官改/$today
