name: test

on:
  schedule:
    - cron:  '* * * * *'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: 获取本仓库源码...
        uses: actions/checkout@main

      - name: test
        run: |
          echo test
